// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230214125642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Core.Domain.Common.ApiRequestBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaRfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Requests", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApiRequestBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Domain.Common.ApiResponseBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Responses", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApiResponseBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateClienteRequest", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiRequestBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Options");

                    b.HasDiscriminator().HasValue("CreateClienteRequest");
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateDocumentoDigitalRequest", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiRequestBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Options");

                    b.HasDiscriminator().HasValue("CreateDocumentoDigitalRequest");
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateDocumentoRequest", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiRequestBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Options");

                    b.HasDiscriminator().HasValue("CreateDocumentoRequest");
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateClienteResponse", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiResponseBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreateClienteResponse");
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateDocumentoDigitalResponse", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiResponseBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreateDocumentoDigitalResponse");
                });

            modelBuilder.Entity("Api.Core.Domain.Requests.CreateDocumentoResponse", b =>
                {
                    b.HasBaseType("Api.Core.Domain.Common.ApiResponseBase");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.HasDiscriminator().HasValue("CreateDocumentoResponse");
                });

            modelBuilder.Entity("Api.Core.Domain.Common.ApiResponseBase", b =>
                {
                    b.HasOne("Api.Core.Domain.Common.ApiRequestBase", null)
                        .WithOne("Response")
                        .HasForeignKey("Api.Core.Domain.Common.ApiResponseBase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Core.Domain.Common.ApiRequestBase", b =>
                {
                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
